version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_API_URL=http://backend:8000 # Adjust if needed
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=bolt://neo4j:7687 # Neo4j connection
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=your_neo4j_password # Replace with a secure password
      # Add other environment variables as needed (e.g., LLM model path)
    depends_on:
      - database
    networks:
      - app-network

  database:
    image: neo4j:latest
    ports:
      - "7474:7474" # Browser interface
      - "7687:7687" # Bolt protocol
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    environment:
      - NEO4J_AUTH=neo4j/your_neo4j_password # Replace with the same secure password
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443" # For HTTPS if you configure it
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # If you have SSL certificates:
      # - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

  mlflow:
    build:
      context: ./mlflow
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  neo4j_data:
  neo4j_logs: